### ISSUE TITLE
addGroupMessage 시 groupId가 없는 groupId면 500 에러가 나옵니다.

### ISSUE THREAD

**Issue by KimGenius** [solapi/solapi-go#1]
혹시나 제가 잘못한걸수도 있으니 확인 부탁드려용
![스크린샷 2020-09-13 오후 5 56 36](https://user-images.githubusercontent.com/29722636/93014245-79a17c00-f5ea-11ea-9137-b4e936b90e53.png)

**Comment by hosysy** [comment]
이건 실제로 인터널 서버에러가 난거네요
백엔드쪽 수정이 필요할 것 같네요!
