### ISSUE TITLE
examples에 uploadFile 에서 코드대로 하면 file NotFound가 나옵니다.

### ISSUE THREAD

**Issue by KimGenius** [solapi/solapi-go#2]
![스크린샷 2020-09-13 오후 6 08 32](https://user-images.githubusercontent.com/29722636/93014447-23cdd380-f5ec-11ea-83b4-f446cfd9c8ca.png)

**Comment by hosysy** [comment]
으음 이상하네..;
맥에서 시도했을땐 잘 되는데
환경이나 그런걸 좀 알수있을까요?

**Comment by KimGenius** [comment]
<img width="1642" alt="스크린샷 2020-10-12 오전 11 13 35" src="https://user-images.githubusercontent.com/29722636/95698165-0ee07080-0c7c-11eb-86e2-8dcf36163247.png">
제가 GoLand 라는 툴을 사용하는데 거기서 실행 버튼으로 실행하면 시작 디렉토리가 달라서 나는 오류같습니다.
혹시나 해서 터미널에서 해당 경로로 이동해서 빌드 후 런하면 잘 작동하네욤 :>
