### ISSUE TITLE
config.json 파일 위치

### ISSUE THREAD

**Issue by wileyday** [solapi/solapi-go#5]
config.json 파일을 golang 패키지 설치 디렉토리에서 읽어오고 있어서 설치된 파일을 찾아서 수정해줘야 하는 불편함이 있습니다.
패키지를 읽어서 사용하는 프로젝트 디렉토리에서 config.json 파일을 우선적으로 찾을 수 있게 수정되면 좋겠습니다.

**Comment by hosysy** [comment]
Config 파일 파라미터로 넘길수있도록 개선

**Comment by doyoung95** [comment]
안녕하세요
docker 환경에서 빌드 후 사용하면 config.json이 누락되어 에러를 던지는 이슈가 있습니다.
더이상 쓰이지 않는 코드로 보입니다!
```
//apirequest/apirequest.go
// line 99


// NewAPIRequest create
func NewAPIRequest() *APIRequest {
	goos := runtime.GOOS
	goVersion := runtime.Version()
	osPlatform := fmt.Sprintf("%s/%s", goos, goVersion)

	request := APIRequest{response: "", statusCode: "", OsPlatform: osPlatform, SdkVersion: sdkVersion}
        //------------- start
	// Read File
	filePath := getConfigFilePath()
	file, err := ioutil.ReadFile(filePath)
	if err != nil {
		log.Fatalln("Error reading")
		return &request
	}

	err = json.Unmarshal(file, &request)
	fmt.Println(request)
	if err != nil {
		log.Fatalln("Error file Unmarshal")
		return &request
	}
       // -------------end
	return &request
}
```

**Comment by Palbahngmiyine** [comment]
@doyoung95 
안녕하세요, SOLAPI 기술지원팀입니다. 혹시 Docker로 빌드하실 때, config.json 누락 에러가 어떤 메시지를 표시하는지 해당 타래에 남겨주시면 확인 후 안내 도와드리겠습니다. 

아래 PR은 위의 사항 확인되면 리뷰 후 처리하겠습니다. 
#8

**Comment by doyoung95** [comment]
@Palbahngmiyine 안녕하세요, docker 빌드시 config.json을 마운트 해주지 않으면 읽지 못해 해당 fatal에러를 발생시킵니다
apirequest/apirequest.go
line 106 - 118
log.Fatalln("Error reading")
log.Fatalln("Error file Unmarshal")
config 값을 지정해주었을때는
config.json 여부에서 에러 없이 관계없이 request에 값이 매핑 되어야 합니다!

 PR  #8 커밋 [83ae56c](https://github.com/solapi/solapi-go/pull/8/commits/83ae56c7e2ff3d0c5f128be985d76d1220364e50)
json.Unmarshal 코드를 주석 처리한 코드를 같이 넘겨 드렸네요
확인이 필요합니다

**Comment by Palbahngmiyine** [comment]
해당 사항은 의도된 사항으로, 실제 Production 환경에서는 config.json을 불러올 수 있는 환경하에서  초기설정 상 config.json을 불러오고 해당 config.json의 값을 기반으로 처리하도록 되어있습니다.

말씀하신 사항은 추후 개선점으로 검토하여 개선될 수 있도록 하겠으며, 혹시라도 config.json가 정상적으로 불러올 수 있는 환경이고, 실제로 config.json을 정상적으로 불러왔는데 오류가 발생하신 사항이신지 확인 부탁드립니다.

**Comment by Palbahngmiyine** [comment]
추가로, 말씀드린 부분에 config.json 관련 설정 기능이 문제가 없다면 해당 PR #8 은 종료 처리하겠습니다.

**Comment by doyoung95** [comment]
@Palbahngmiyine 확인했습니다!

**Comment by Palbahngmiyine** [comment]
네 감사합니다, 말씀드린 의견은 빠르게 반영될 수 있도록 하겠으며, PR은 종료처리 하겠습니다. 감사합니다.

**Comment by Palbahngmiyine** [comment]
@doyoung95 안녕하세요 회원님, 관련 업데이트 내용이 늦어서 송구하다는 말씀을 드립니다.

금일부터 말씀하신 내용이 반영된 SOLAPI Golang SDK v2.0.0이 릴리즈 되었습니다. `go get github.com/solapi/solapi-go/v2` 명령어를 통해 바로 만나보실 수 있으며, 관련한 [예제](https://github.com/solapi/solapi-go/tree/master/v2/_examples) 또한 작성되었으니 혹여라도 반영이 필요하신 경우 관련 예제 폴더를 통해 업무에 참고 해 주시길 바라겠습니다.

감사합니다.
